bases:
  - ../../base

commonLabels:
  variant: development

commonAnnotations:
  description: Taco Cloud project
  source: kustomize
  team: sanacloud

namePrefix: poc-
nameSuffix: -dev
patchesStrategicMerge:
  - deployment.yaml