apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml

labels:
- pairs:
    kind: front
    lang: spring
    project: taco-cloud
    region: westeurope

commonAnnotations:
  description: Taco Cloud project
  source: kustomize
  team: sanacloud

images:
- digest: sha256:6148cfd002a782b9be43d5bbe3b078a0b745d600891b1ad83802699397cb440e
  name: app-image
  newName: docker.io/georgevazj/taco-cloud
namespace: argocd

replicas:
- count: 3
  name: taco-cloud
nameSuffix: -playground
