apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- route.yaml
- service.yaml

labels:
- pairs:
    kind: front
    lang: spring
    project: taco-cloud
    region: westeurope

commonAnnotations:
  description: Taco Cloud project
  source: kustomize
  team: sanacloud

images:
- digest: sha256:448d309d0348de2487527334f9b054a359a674996d831be7dbe10801978abe66
  name: app-image
  newName: docker.io/georgevazj/taco-cloud
namespace: argocd
